<!---
Sleep Journal v.0

Copyright (C) 1989, 1991 Free Software Foundation, Inc.  
51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

Everyone is permitted to copy and distribute verbatim copies
of this license document, but changing it is not allowed.
--->

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="apple-touch-icon-precomposed" href="_/img/touch-icon-iphone-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="76x76" href="_/img/touch-icon-iphone-retina-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="120x120" href="_/img/touch-icon-ipad-precomposed.png">
<link rel="apple-touch-icon-precomposed" sizes="152x152" href="_/img/touch-icon-ipad-retina-precomposed.png">
<link rel="apple-touch-startup-image" href="_/img/startup.png?v=3">
<link rel="stylesheet" type="text/css" href="_/css/reset.css">
<link rel="stylesheet" type="text/css" href="_/css/sleepjournal.css?v=4">
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="_/js/css3-mediaqueries.js"></script>
<script src="_/js/sleepjournal.js"></script>
